### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by wouter-MC** [Chickenpowerrr/RankSync#1]
No documentations to be found, not even the API has documentation.

**Comment by Chickenpowerrr** [comment]
I might get documented in the future

**Comment by Chickenpowerrr** [comment]
I've documented the API for you in the following commits:
https://github.com/Chickenpowerrr/RankSync/commit/be5134afe8a719940c156012cf7cc540d416b6e7
https://github.com/Chickenpowerrr/RankSync/commit/2909a1849d0d20c5dae7d2934a46089d779a2031
