### ISSUE TITLE
Add a reload command

### ISSUE THREAD

**Issue by EvanSchleret** [Chickenpowerrr/RankSync#18]
**Is your feature request related to a problem? Please describe.**
Add a reload command

**Describe the solution you'd like**
Everything in the title

**Describe alternatives you've considered**
Restart the server.

**Additional context**
N/A

**Comment by Chickenpowerrr** [comment]
The plugin does not support reloads for technical reasons. I'll try to see if I can resolve it in a future update, the chances of a config reload command are higher right now.
