### ISSUE TITLE
config.yml keeps getting reset

### ISSUE THREAD

**Issue by Auriosi** [Chickenpowerrr/RankSync#19]
**Describe the bug**
Everytime I modify the config.yml file, it gets reset at start, and log says that the token is incorrect, even though it keeps resetting it.

**To Reproduce**
1. Set the token and guild id to what they are supposed to be
2. If not done on server, overwrite the old file with the new one
3. Start the server

**Expected behavior**
I expect it to keep config.yml how I set it

**Screenshots**

**Server (please complete the following information):**
 - Plugin version: 1.4.0
 - MySQL version: Not used?
 - Spigot version: 1.15.2
 - Server is run in a Docker container, but that shouldn't affect it.

**Additional context**
Resets the entire file, not just the ID and token.

**Comment by Chickenpowerrr** [comment]
I have had other people reporting this issue and it looks like this issue happens when the config contains some invalid YAML syntax. This will hopefully be resolved in a future update.
