### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by DeusDrizzyy** [Chickenpowerrr/RankSync#23]
> [19:30:45 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Illegal group reference
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
> [19:30:45 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> [19:30:45 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> [19:30:45 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> [19:30:45 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
> [19:30:45 WARN]: Caused by: java.lang.IllegalArgumentException: Illegal group reference
> [19:30:45 WARN]: at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
> [19:30:45 WARN]: at java.util.regex.Matcher.replaceAll(Matcher.java:955)
> [19:30:45 WARN]: at java.lang.String.replaceAll(String.java:2223)
> [19:30:45 WARN]: at com.gmail.chickenpowerrr.ranksync.discord.language.Translation.getTranslation(Translation.java:45)
> [19:30:45 WARN]: at com.gmail.chickenpowerrr.ranksync.discord.command.LinkCommand.execute(LinkCommand.java:84)
> [19:30:45 WARN]: at com.gmail.chickenpowerrr.ranksync.discord.event.DiscordEventListeners.lambda$onEvent$3(DiscordEventListeners.java:89)
> [19:30:45 WARN]: at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
> [19:30:45 WARN]: ... 8 more

Discord members with names that contain special characters and use !Link receive only the message discord-link-command-rightthere and return this error on the console.

**Comment by MCAlagaesia** [comment]
https://pastebin.com/GbiLDuY2

Can replicate. Reported unofficially via Discord on the 1st of February this year.

The issue was indeed the display name. In my case, the username was `rep$aC uY`, so it appears to be an issue with your regular expressions (`$`). The user changed their username and was able to link their account just fine.
