### ISSUE TITLE
Console Error on startup

### ISSUE THREAD

**Issue by SoraShiunin** [Chickenpowerrr/RankSync#5]
**Describe the bug**
Error in Console (Is it up to date?)

**To Reproduce**
1. Start the server
2. See error

**Expected behavior**
No errors in Console

**Screenshots**
Error : https://pastebin.com/rre2PMWz

**Server (please complete the following information):**
 - Plugin version 1.2.0
 - Spigot version [e.g. 1.13.2]

**Comment by Chickenpowerrr** [comment]
Hello SoraShiunin,

if you see this message it means that your Discord Token in your config.yml isn't a valid Discord Bot token. To get a valid one, please check the following page: https://github.com/Chickenpowerrr/RankSync/wiki/Getting-a-Discord-Token
